/**
 * Shared utilities for platform conversion scripts
 */

import { readdir, stat, mkdir } from "node:fs/promises";
import { join } from "node:path";
import {
  validatePath,
  sanitizeFilename,
  readFileSafe,
  writeFileSafe,
  validateFilename,
} from "./security";

export const PLUGIN_VERSION = "0.7.4";

export const AGENT_CATEGORIES = ["review", "research", "design", "workflow", "docs"] as const;

export function generationHeader(source: string): string {
  return `<!-- Generated by lavra v${PLUGIN_VERSION} -->
<!-- Source: ${source} -->
<!-- DO NOT EDIT - changes will be overwritten on next install -->

`;
}

function injectHeaderAfterFrontmatter(content: string, header: string): string {
  if (!content.startsWith("---\n")) {
    return header + content;
  }

  const endIdx = content.indexOf("\n---\n", 4);
  if (endIdx === -1) {
    return header + content;
  }

  const fmEnd = endIdx + 5; // include closing "\n---\n"
  return content.slice(0, fmEnd) + "\n" + header + content.slice(fmEnd);
}

/**
 * Converts skills from SOURCE_DIR to OUTPUT_DIR.
 * pathReplacement controls how .claude/skills/ references are rewritten.
 */
export async function convertSkills(
  sourceDir: string,
  outputDir: string,
  pathReplacement: string
): Promise<void> {
  console.log("Converting skills...");

  const skillsDir = validatePath(sourceDir, "skills");
  const outDir = validatePath(outputDir, "skills");

  await mkdir(outDir, { recursive: true, mode: 0o755 });

  const skillDirs = await readdir(skillsDir, { withFileTypes: true });
  const skills = skillDirs
    .filter((d) => d.isDirectory() && d.name !== "optional")
    .map((d) => d.name);

  await Promise.all(
    skills.map(async (skill) => {
      const skillDir = validatePath(skillsDir, skill);
      const outputSkillDir = validatePath(outDir, sanitizeFilename(skill));

      const skillMd = join(skillDir, "SKILL.md");
      try {
        await stat(skillMd);
      } catch {
        return;
      }

      await mkdir(outputSkillDir, { recursive: true, mode: 0o755 });

      const raw = await readFileSafe(skillMd);
      const hooksReplacement = pathReplacement.replace(/skills\/$/, "hooks/");
      const content = raw
        .replace(/\.claude\/skills\//g, pathReplacement)
        .replace(/ls \.claude\/skills\//g, `ls ${pathReplacement}`)
        .replace(/\.claude\/hooks\//g, hooksReplacement);

      const outputSkillMd = join(outputSkillDir, "SKILL.md");
      const header = generationHeader(`${skill}/SKILL.md`);
      await writeFileSafe(
        outputSkillMd,
        injectHeaderAfterFrontmatter(content, header),
        0o644
      );
      console.log(`  ✓ ${skill}/SKILL.md`);
    })
  );

  console.log(`  Converted ${skills.length} skills\n`);
}
