#!/bin/bash
#
# Uninstall lavra plugin from Gemini CLI
#
# Usage:
#   Called by uninstall.sh -gemini [target]
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Default to ~/.config/gemini if no argument provided
if [ $# -eq 0 ]; then
  TARGET="$HOME/.config/gemini"
  GLOBAL_UNINSTALL=true
else
  TARGET="$1"
  GLOBAL_UNINSTALL=false
fi

# Resolve to absolute path
if [ ! -d "$TARGET" ]; then
  echo "[!] Error: Target directory does not exist: $TARGET"
  exit 1
fi

TARGET="$(cd "$TARGET" && pwd)"

echo "🗑️  lavra Gemini CLI Uninstaller"
echo ""
echo "Target: $TARGET"
if [ "$GLOBAL_UNINSTALL" = true ]; then
  echo "Type: Global uninstallation"
else
  echo "Type: Project-specific uninstallation"
fi
echo ""

# Warning
echo "⚠️  This will remove:"
echo "  - All hooks (hooks/)"
echo "  - All commands (commands/*.toml)"
echo "  - All agents (agents/)"
echo "  - All skills (skills/)"
echo "  - Memory scripts (recall.sh, knowledge-db.sh)"
echo ""
echo "Note: Your knowledge.jsonl database will be preserved"
echo ""

read -p "Continue? (y/N) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
  echo "Uninstall cancelled."
  exit 0
fi

echo ""
echo "🗑️  Removing files..."

# Remove hooks
if [ -d "$TARGET/hooks" ]; then
  for hook in auto-recall.sh memory-capture.sh subagent-wrapup.sh memory-sanitize.sh; do
    if [ -f "$TARGET/hooks/$hook" ]; then
      rm "$TARGET/hooks/$hook"
      echo "  ✓ Removed $hook"
    fi
  done
fi

# Remove commands (.toml files)
if [ -d "$TARGET/commands" ]; then
  # Remove all .toml files generated by plugin
  find "$TARGET/commands" -type f -name "*.toml" -exec grep -l "Generated by lavra" {} \; -delete 2>/dev/null || true
  echo "  ✓ Removed commands (.toml)"
fi

# Remove agents
if [ -d "$TARGET/agents" ]; then
  for category in review research design workflow docs; do
    if [ -d "$TARGET/agents/$category" ]; then
      find "$TARGET/agents/$category" -type f -name "*.md" -exec grep -l "Generated by lavra" {} \; -delete 2>/dev/null || true
    fi
  done
  echo "  ✓ Removed agents"
fi

# Remove skills
if [ -d "$TARGET/skills" ]; then
  # List of known plugin skills
  PLUGIN_SKILLS=(
    git-worktree brainstorming create-agent-skills agent-native-architecture
    lavra-knowledge agent-browser andrew-kane-gem-writer dhh-rails-style
    dspy-ruby every-style-editor file-todos frontend-design gemini-imagegen
    rclone
  )

  for skill in "${PLUGIN_SKILLS[@]}"; do
    if [ -d "$TARGET/skills/$skill" ]; then
      # Verify it's a plugin skill by checking for generation marker
      if grep -q "Generated by lavra" "$TARGET/skills/$skill/SKILL.md" 2>/dev/null; then
        rm -rf "$TARGET/skills/$skill"
        echo "  ✓ Removed skill: $skill"
      fi
    fi
  done
fi

# Remove memory scripts (keep knowledge.jsonl - that's user data)
if [ -d "$TARGET/.lavra/memory" ]; then
  # Remove plugin scripts only
  if [ -f "$TARGET/.lavra/memory/recall.sh" ]; then
    rm "$TARGET/.lavra/memory/recall.sh"
    echo "  ✓ Removed recall.sh"
  fi
  if [ -f "$TARGET/.lavra/memory/knowledge-db.sh" ]; then
    rm "$TARGET/.lavra/memory/knowledge-db.sh"
    echo "  ✓ Removed knowledge-db.sh"
  fi
  if [ -f "$TARGET/.lavra/memory/memory-sanitize.sh" ]; then
    rm "$TARGET/.lavra/memory/memory-sanitize.sh"
    echo "  ✓ Removed memory-sanitize.sh"
  fi

  # Note: knowledge.jsonl and knowledge.archive.jsonl are preserved (user data)
  if [ -f "$TARGET/.lavra/memory/knowledge.jsonl" ]; then
    echo "  ⊘ Kept knowledge.jsonl (user data preserved)"
  fi
fi

echo ""
echo "✅ Uninstall complete!"
echo ""

if [ "$GLOBAL_UNINSTALL" = true ]; then
  echo "Global uninstallation complete. Gemini CLI no longer has access to lavra."
else
  echo "Project-specific uninstallation complete for: $TARGET"
fi
