#!/usr/bin/env bun

/**
 * convert-cortex.ts
 * Converts beads-compound plugin files from Claude Code format to Cortex Code format
 *
 * Security controls:
 * - Path traversal protection
 * - File size limits (10MB)
 * - YAML SAFE_SCHEMA parsing
 * - Model name validation
 * - Explicit file permissions (644)
 */

import { readdir, mkdir } from "node:fs/promises";
import { join } from "node:path";
import {
  validatePath,
  sanitizeFilename,
  readFileSafe,
  writeFileSafe,
  validateModelName,
  validateFilename,
} from "./shared/security";
import {
  parseFrontmatter,
  extractBody,
  buildMarkdown,
} from "./shared/yaml-parser";
import { mapToCortex } from "./shared/model-mapping";

const PLUGIN_VERSION = "0.6.0";
const SOURCE_DIR = join(import.meta.dir, "../plugins/beads-compound");
const OUTPUT_DIR = join(import.meta.dir, "../plugins/beads-compound/cortex");

/**
 * Converts commands (direct copy - formats are identical)
 */
async function convertCommands() {
  console.log("Converting commands...");

  const commandsDir = validatePath(SOURCE_DIR, "commands");
  const outputDir = validatePath(OUTPUT_DIR, "commands");

  await mkdir(outputDir, { recursive: true, mode: 0o755 });

  const files = await readdir(commandsDir);
  const mdFiles = files.filter((f) => f.endsWith(".md"));

  // Parallel processing for performance
  await Promise.all(
    mdFiles.map(async (file) => {
      if (!validateFilename(file)) {
        console.warn(`  ⚠️  Skipping invalid filename: ${file}`);
        return;
      }

      const sourcePath = validatePath(commandsDir, file);
      const outputPath = validatePath(outputDir, sanitizeFilename(file));

      const content = await readFileSafe(sourcePath);

      // Add generation header
      const withHeader = `<!-- Generated by beads-compound v${PLUGIN_VERSION} -->
<!-- Source: ${file} -->
<!-- DO NOT EDIT - changes will be overwritten on next install -->

${content}`;

      await writeFileSafe(outputPath, withHeader, 0o644);
      console.log(`  ✓ ${file}`);
    })
  );

  console.log(`  Converted ${mdFiles.length} commands\n`);
}

/**
 * Converts agents (field mapping required)
 */
async function convertAgents() {
  console.log("Converting agents...");

  const categories = ["review", "research", "design", "workflow", "docs"];
  let totalConverted = 0;

  // Create all category directories upfront
  await Promise.all(
    categories.map((category) =>
      mkdir(join(OUTPUT_DIR, "agents", category), {
        recursive: true,
        mode: 0o755,
      })
    )
  );

  // Process each category in parallel
  await Promise.all(
    categories.map(async (category) => {
      const categoryDir = validatePath(SOURCE_DIR, `agents/${category}`);
      const outputCategoryDir = validatePath(OUTPUT_DIR, `agents/${category}`);

      const files = await readdir(categoryDir);
      const mdFiles = files.filter((f) => f.endsWith(".md"));

      // Process files in parallel
      await Promise.all(
        mdFiles.map(async (file) => {
          if (!validateFilename(file)) {
            console.warn(`  ⚠️  Skipping invalid filename: ${file}`);
            return;
          }

          const sourcePath = validatePath(categoryDir, file);
          const outputPath = validatePath(outputCategoryDir, sanitizeFilename(file));

          const content = await readFileSafe(sourcePath);
          const frontmatter = parseFrontmatter(content);
          const body = extractBody(content);

          // Transform frontmatter for Cortex Code
          const cortexFrontmatter: Record<string, any> = {};

          // Preserve name if present
          if (frontmatter.name) {
            cortexFrontmatter.name = frontmatter.name;
          }

          // Preserve description
          if (frontmatter.description) {
            cortexFrontmatter.description = frontmatter.description;
          }

          // Map model if present and not inherit
          if (frontmatter.model && frontmatter.model !== "inherit") {
            const mappedModel = mapToCortex(frontmatter.model);
            validateModelName(mappedModel);
            cortexFrontmatter.model = mappedModel;
          } else {
            cortexFrontmatter.model = "inherit";
          }

          // Preserve tools if present
          if (frontmatter.tools) {
            cortexFrontmatter.tools = frontmatter.tools;
          }

          // Build output
          const output = buildMarkdown(cortexFrontmatter, body);

          // Add generation header
          const withHeader = `<!-- Generated by beads-compound v${PLUGIN_VERSION} -->
<!-- Source: ${category}/${file} -->
<!-- DO NOT EDIT - changes will be overwritten on next install -->

${output}`;

          await writeFileSafe(outputPath, withHeader, 0o644);
          console.log(`  ✓ ${category}/${file}`);
        })
      );

      totalConverted += mdFiles.length;
    })
  );

  console.log(`  Converted ${totalConverted} agents\n`);
}

/**
 * Converts skills (direct copy)
 */
async function convertSkills() {
  console.log("Converting skills...");

  const skillsDir = validatePath(SOURCE_DIR, "skills");
  const outputDir = validatePath(OUTPUT_DIR, "skills");

  await mkdir(outputDir, { recursive: true, mode: 0o755 });

  const skillDirs = await readdir(skillsDir, { withFileTypes: true });
  const skills = skillDirs.filter((d) => d.isDirectory()).map((d) => d.name);

  // Process each skill directory in parallel
  await Promise.all(
    skills.map(async (skill) => {
      const skillDir = validatePath(skillsDir, skill);
      const outputSkillDir = validatePath(outputDir, sanitizeFilename(skill));

      await mkdir(outputSkillDir, { recursive: true, mode: 0o755 });

      // Copy SKILL.md
      const skillMd = join(skillDir, "SKILL.md");
      const outputSkillMd = join(outputSkillDir, "SKILL.md");

      try {
        const content = await readFileSafe(skillMd);

        // Add generation header
        const withHeader = `<!-- Generated by beads-compound v${PLUGIN_VERSION} -->
<!-- Source: ${skill}/SKILL.md -->
<!-- DO NOT EDIT - changes will be overwritten on next install -->

${content}`;

        await writeFileSafe(outputSkillMd, withHeader, 0o644);
        console.log(`  ✓ ${skill}/SKILL.md`);
      } catch (err) {
        console.warn(`  ⚠️  Skipping ${skill} (no SKILL.md found): ${err}`);
      }
    })
  );

  console.log(`  Converted ${skills.length} skills\n`);
}

/**
 * Main conversion function
 */
async function main() {
  console.log("🔄 Converting beads-compound to Cortex Code format\n");
  console.log(`Source: ${SOURCE_DIR}`);
  console.log(`Output: ${OUTPUT_DIR}\n`);

  try {
    // Create root output directory
    await mkdir(OUTPUT_DIR, { recursive: true, mode: 0o755 });

    // Run all conversions in parallel (no MCP docs for Cortex)
    await Promise.all([
      convertCommands(),
      convertAgents(),
      convertSkills(),
    ]);

    console.log("✅ Conversion complete!");
    console.log(`\nGenerated files in: ${OUTPUT_DIR}`);

    // Only show manual copy instructions if running standalone (not during install)
    if (!process.env.BEADS_INSTALLING) {
      console.log("\nNext steps:");
      console.log("1. Review the generated files");
      console.log("2. Copy to your Cortex Code project:");
      console.log(`   cp -r ${OUTPUT_DIR}/* <project>/.cortex/`);
    }
  } catch (err: any) {
    console.error("❌ Conversion failed:", err.message);
    process.exit(1);
  }
}

// Run if executed directly
if (import.meta.main) {
  main();
}

export { convertCommands, convertAgents, convertSkills };
